### ISSUE TITLE
​Why don't it have code and source of the first version?​

### ISSUE THREAD

**Issue by 2323948941** [jermwatt/mlrefined#24]
![8f3700461aadea16e0a3501ce1a542c](https://user-images.githubusercontent.com/99175351/177703459-426d58f4-777a-4067-8731-f75538dc10f0.jpg)

**Comment by neonwatty** [comment]
Hi!  In addition to the content upgrades with the 2nd edition of the text, we made a set of major tech stack upgrades so that as much of the text (including interactive demos, code libraries, animations, jupyter notebooks, etc.,) could be freely distributed online by all.  Unfortunately this was not possible to do with the 1st edition of the text.

However the 2nd edition of the text contains virtually all examples contained in the 1st edition - and those code examples are indeed in this repository.  If you need help finding a particular example or set of examples please open a targeted issue about them.

**Comment by 2323948941** [comment]
Ok, thank you for your answer


&nbsp;
------------------

謙
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Jeremy Watt"; 
Sendtime: Friday, Jul 8, 2022 7:23 AM
To: "jermwatt/machine_learning_refined"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [jermwatt/machine_learning_refined] ​Why don&#39;t it have code and source of the first version?​ (Issue #24)





 
Hi!  In addition to the content upgrades with the 2nd edition of the text, we made a set of major tech stack upgrades so that as much of the text (including interactive demos, code libraries, animations, jupyter notebooks, etc.,) could be freely distributed online by all.  Unfortunately this was not possible to do with the 1st edition of the text.
 
However the 2nd edition of the text contains virtually all examples contained in the 1st edition - and those code examples are indeed in this repository.  If you need help finding a particular example or set of examples please open a targeted issue about them.
