### ISSUE TITLE
Missing 2-4 chapters' exercise folders for 2nd edition

### ISSUE THREAD

**Issue by JulieWasNotAvailable** [jermwatt/mlrefined#26]
Hello!

I have just started to read the book and wanted to try out some exercises. But there is only information about execrises starting from chapter 5 in here. So, I just wanted to ask, if they were supposed to be there originally, or not.

**Comment by neonwatty** [comment]
Hi! 

Yes, there is information on exercises 2-4 (in the exercises and text body) but no notebook wrappers.  

This was a design choice made at launch (e.g., a lot of pencil and paper exercises in 2-4, the isolation of optimization).

However maybe its time we update our thoughts on that design choice. 

Are there particular exercises that need a lift in your mind?  Would like wrappers (for coding exercises) in these chapters?

**Comment by JulieWasNotAvailable** [comment]
Well, to be honest, I'm only a starter and I have basic understanding of python. So, for people like me, would be pretty cool to have wrappers for all of them (if I understand right that by wrappers you mean notes to help finding the solution to the exercise).

Could be also really great to have names of topics of python that are needed for exercises. 

But I'm not sure, how many of learners like me there are all in all; it may be irrational to put effort for like 3 or 4 people, who stumble upon a book in a year.

Last, but not least, solutions for coding exercises could be really helpful.

**Comment by neonwatty** [comment]
Gotcha!  

- By "wrappers" I mean jupyter notebooks like [this one for chapter 5](https://github.com/jermwatt/machine_learning_refined/blob/gh-pages/mlrefined_exercises/ed_2/chapter_5/chapter_5_exercises.ipynb) that gets you started with a bit of the code (e.g., data loading, manipulation, plotting)

 - To get started with the textbook exercises - here's the list of Python need-to-know: there "aren't that many" in terms of enumeration, but they're important to know well
   1. fundamental Python concepts (syntax, data structures, installing packages, etc.,)
       - for a primer on Python, I'd recommend any highly rated "Python" or "Python for data science" course on Udemy or [Mosh's great Python overview]
       - (https://codewithmosh.com/p/python-programming-course-beginners)
   2.  Jupyter notebook - how to start, operate, and stop one
       - this is quick with 1) out of the way - a top Youtbube video will do the trick
   2.  Matplotlib - for plotting pictures (this is how all the pictures in the book are generated).  
       - see previous comment - same deal!
  4.  Numpy - a popular numerical compute library (for vectors, matrices, tensors)
       - [Youtube](https://www.youtube.com/watch?v=QUT1VHiLmmI) or a comprehensive Udemy course on Python for Data Science will do the trick here
  5.  Autograd - you can think of this as a slightly extended version of nump wrapped in a simple, elegant, auto-differentiator (so you can take derivatives of functions consisting of numpy objects).  
       - we have a walkthrough of [how to use autograd here](https://github.com/jermwatt/autograd_tutorials)

Some other resources that might be helpful
- [a quick primer on computational maths](https://github.com/jermwatt/computational_maths)

I would stress - start by first solidfying your Python foundation - it'll payoff and make the rest of the list a synch!

- I'll whip up wrappers to chapters 2- 4 this week - I'll reply in this issue to update you when they're up.


- Visa-vis solutions, because the text is used in universities for instruction I cannot hand them out here.  However I can point you to the correct owner on the publisher side who - after verification - can provide them to you.

**Comment by JulieWasNotAvailable** [comment]
Thank you a lot for a quick answer and useful sources!

However, I didn't understand the very last point about visa-vis solutions, could you clarify on that?

**Comment by neonwatty** [comment]
Just pushed wrappers for key problems in chaps 2- 4 to the exercises folder!  

Visa-vis the solutions - at present we are used at a number of universities whose instructors will regularly assign homework problems from the text.  So because of this the solutions are gated for now.

In order to gain access to solutions you will need to show Cambridge (the publisher) that ou are not currently / in the near future enrolled in an ML course employing the book.   You can follow [this link](https://www.cambridge.org/highereducation/books/machine-learning-refined/0A64B2370C2F7CE3ACF535835E9D7955/resources/general-resources/BBC1F3B4D376C7EE2B18E7E51BD26E48) to register your book and communicate with Cambridge's team to do this, and gain access to solutions as an independent reader.
 
Let me know of any troubles in this direction and I can try to fast track your request with them.

**Comment by neonwatty** [comment]
Closing this for now - let me know if I can help you further!
